name: PR Images Preview

on:
  workflow_run:
    workflows: [ "Generate graphics" ]
    types:
      - completed
    branches-ignore:
      - 'main'


jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v6
      - name: Set up temporary branch
        id: branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git branch --set-upstream-to=origin/pr-images  pr-images || true
          git checkout pr-images
          git pull origin pr-images --rebase
      - name: Download PR Artifact
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
          run-id: ${{ github.event.workflow_run.id }}
          name: images
          path: images
      - name: Check for changes
        id: changed
        run: |
          # Refresh index so git diff-index doesn't return true just because of timestamp changes
          git update-index --refresh
          
          # Decide if anything has changed
          if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected."
          echo "files_changed=true" >> $GITHUB_OUTPUT
          else
          echo "No changes."
          echo "files_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Download PR Artifact
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
          run-id: ${{ github.event.workflow_run.id }}
          name: pr
      - name: Store PR id as variable
        id: pr
        run: |
          echo "id=$(<pr_number)" >> $GITHUB_OUTPUT
          rm pr_number
      - name: Push to temporary branch
        if: steps.changed.outputs.files_changed == 'true'
        id: push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add images/*svg
          git commit -m "Images for #${{ steps.pr.outputs.id }}}"
          git push origin -u pr-images
          echo hash=`git rev-parse HEAD` >> $GITHUB_OUTPUT
      - name: Update PR status comment with link
        if: steps.changed.outputs.files_changed == 'true'
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ðŸš€ PR Preview ![generated image](../blob/${{ steps.push.outputs.hash }}/images/spring-quarkus-perf-comparison-latest-throughput-light.svg?raw=true)
          number: ${{ steps.pr.outputs.id }}
      - name: Update PR status comment with absence of link
        if: steps.changed.outputs.files_changed == 'false'
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
           This PR would not change any of the generated images.
          number: ${{ steps.pr.outputs.id }}